// Contenido bilingüe del formulario de diagnóstico.
import type { Lang } from "@/lib/content";

export const formContent = {
  es: {
    stepTitles: [
      "Datos de contacto",
      "Tu negocio",
      "Tu mercado",
      "Situación actual",
      "Tu objetivo",
    ],
    progress: (s: number, t: number, title: string) => `Paso ${s} de ${t} — ${title}`,
    prev: "Anterior",
    next: "Siguiente",
    submit: "Enviar solicitud",
    sending: "Enviando...",
    select: "Selecciona...",
    contactHint: "Empezamos por tus datos de contacto. Te escribo yo personalmente — sin spam.",
    consentPre: "He leído y acepto la ",
    consentLink: "política de privacidad",
    consentPost: ".",
    errors: {
      nombre: "Nombre obligatorio",
      empresa: "Empresa obligatoria",
      pais: "País obligatorio",
      sector: "Selecciona un sector",
      required: "Requerido",
      problema: "Describe brevemente tu problema",
      objetivo: "Selecciona al menos un objetivo",
      email: "Email no válido",
      telefono: "Teléfono obligatorio",
      consent: "Debes aceptar la política de privacidad",
      sendFail: "No se pudo enviar. Inténtalo de nuevo.",
      connFail: "Error de conexión. Comprueba tu red e inténtalo de nuevo.",
    },
    labels: {
      nombre: "Nombre completo *",
      empresa: "Empresa *",
      web: "Sitio web",
      pais: "País *",
      sector: "Sector *",
      tipoNegocio: "Tipo de negocio *",
      tamanoEquipo: "Tamaño del equipo *",
      volumenLeads: "Leads al mes (aproximado) *",
      crmActual: "CRM que usas hoy *",
      usaWhatsapp: "¿Usas WhatsApp para ventas? *",
      tiempoPropuesta: "¿Cuánto tardas en enviar una propuesta? *",
      problema: "¿Cuál es tu principal problema hoy? *",
      objetivo: "¿Qué quieres resolver? (máx. 2) *",
      urgencia: "Urgencia *",
      presupuesto: "Presupuesto estimado *",
      email: "Email *",
      telefono: "Teléfono (con prefijo) *",
      comoConociste: "¿Cómo me conociste? *",
      notas: "Algo que quieras añadir (opcional)",
    },
    ph: {
      nombre: "Tu nombre",
      empresa: "Nombre de tu empresa",
      web: "https://tuempresa.com",
      pais: "España, México, Colombia...",
      problema: "Descríbelo solo en una o dos frases...",
      email: "tu@empresa.com",
      telefono: "+34 600 000 000",
      notas: "Cualquier detalle adicional que creas relevante...",
    },
    opts: {
      sector: [
        ["salud", "Salud / Clínicas"],
        ["formacion", "Formación / Cursos"],
        ["eventos", "Eventos"],
        ["consultoria", "Consultoría / Servicios profesionales"],
        ["agencia", "Agencia / Marketing"],
        ["retail", "Retail / Ecommerce"],
        ["otro", "Otro"],
      ],
      tipoNegocio: [
        ["b2b", "B2B (vendes a empresas)"],
        ["b2c", "B2C (vendes a consumidores)"],
        ["ambos", "Ambos"],
      ],
      tamanoEquipo: [
        ["solo", "Solo / Freelance"],
        ["2-5", "2 a 5 personas"],
        ["6-20", "6 a 20 personas"],
        ["20+", "Más de 20"],
      ],
      volumenLeads: [
        ["<10", "Menos de 10"],
        ["10-50", "Entre 10 y 50"],
        ["50-200", "Entre 50 y 200"],
        ["200+", "Más de 200"],
      ],
      crmActual: [
        ["ninguno", "Ninguno"],
        ["gohighlevel", "Go High Level"],
        ["hubspot", "HubSpot"],
        ["salesforce", "Salesforce"],
        ["pipedrive", "Pipedrive"],
        ["otro", "Otro"],
      ],
      usaWhatsapp: [
        ["si", "Sí, activamente"],
        ["si-sin-sistema", "Sí, pero sin sistema"],
        ["no", "No"],
      ],
      tiempoPropuesta: [
        ["<1h", "Menos de 1 hora"],
        ["1-8h", "Entre 1 y 8 horas"],
        ["1-3d", "Entre 1 y 3 días"],
        ["+3d", "Más de 3 días"],
      ],
      objetivo: [
        "Cualificar mejor mis leads",
        "Automatizar el seguimiento",
        "Reducir tiempo en propuestas",
        "Ordenar mi CRM",
        "Montar un sistema desde cero",
        "Otro",
      ],
      urgencia: [
        ["prisa", "Tengo prisa, quiero avanzar ya (< 30 días)"],
        ["1-3meses", "Estoy planificando para 1-3 meses"],
        ["explorando", "Estoy explorando opciones"],
      ],
      presupuesto: [
        ["<1000", "Menos de 1.000 €"],
        ["1000-3000", "Entre 1.000 € y 3.000 €"],
        ["3000-7000", "Entre 3.000 € y 7.000 €"],
        [">7000", "Más de 7.000 €"],
      ],
      comoConociste: [
        ["linkedin", "LinkedIn"],
        ["google", "Google / SEO"],
        ["referido", "Me lo recomendó alguien"],
        ["redes", "Redes sociales"],
        ["otro", "Otro"],
      ],
    },
    success: {
      title: "Recibido. Te escribo en menos de 24 h.",
      body: "He recibido tu diagnóstico. Si quieres avanzar más rápido, puedes agendar directamente en mi calendario.",
      button: "Reserva tu hueco ahora",
      note: "O espera mi email. Revisaré tu solicitud hoy mismo.",
    },
  },

  en: {
    stepTitles: [
      "Contact details",
      "Your business",
      "Your market",
      "Current situation",
      "Your goal",
    ],
    progress: (s: number, t: number, title: string) => `Step ${s} of ${t} — ${title}`,
    prev: "Back",
    next: "Next",
    submit: "Send request",
    sending: "Sending...",
    select: "Select...",
    contactHint: "Let's start with your contact details. I'll reach out personally — no spam.",
    consentPre: "I have read and accept the ",
    consentLink: "privacy policy",
    consentPost: ".",
    errors: {
      nombre: "Name is required",
      empresa: "Company is required",
      pais: "Country is required",
      sector: "Choose a sector",
      required: "Required",
      problema: "Briefly describe your problem",
      objetivo: "Select at least one goal",
      email: "Invalid email",
      telefono: "Phone is required",
      consent: "You must accept the privacy policy",
      sendFail: "Couldn't send. Please try again.",
      connFail: "Connection error. Check your network and try again.",
    },
    labels: {
      nombre: "Full name *",
      empresa: "Company *",
      web: "Website",
      pais: "Country *",
      sector: "Sector *",
      tipoNegocio: "Business type *",
      tamanoEquipo: "Team size *",
      volumenLeads: "Leads per month (approx.) *",
      crmActual: "CRM you use today *",
      usaWhatsapp: "Do you use WhatsApp for sales? *",
      tiempoPropuesta: "How long does it take you to send a proposal? *",
      problema: "What's your main problem today? *",
      objetivo: "What do you want to solve? (max 2) *",
      urgencia: "Urgency *",
      presupuesto: "Estimated budget *",
      email: "Email *",
      telefono: "Phone (with country code) *",
      comoConociste: "How did you find me? *",
      notas: "Anything you'd like to add (optional)",
    },
    ph: {
      nombre: "Your name",
      empresa: "Your company name",
      web: "https://yourcompany.com",
      pais: "Spain, Mexico, Colombia...",
      problema: "Describe it in just one or two sentences...",
      email: "you@company.com",
      telefono: "+34 600 000 000",
      notas: "Any extra detail you think is relevant...",
    },
    opts: {
      sector: [
        ["salud", "Healthcare / Clinics"],
        ["formacion", "Education / Courses"],
        ["eventos", "Events"],
        ["consultoria", "Consulting / Professional services"],
        ["agencia", "Agency / Marketing"],
        ["retail", "Retail / Ecommerce"],
        ["otro", "Other"],
      ],
      tipoNegocio: [
        ["b2b", "B2B (you sell to businesses)"],
        ["b2c", "B2C (you sell to consumers)"],
        ["ambos", "Both"],
      ],
      tamanoEquipo: [
        ["solo", "Solo / Freelance"],
        ["2-5", "2 to 5 people"],
        ["6-20", "6 to 20 people"],
        ["20+", "More than 20"],
      ],
      volumenLeads: [
        ["<10", "Fewer than 10"],
        ["10-50", "Between 10 and 50"],
        ["50-200", "Between 50 and 200"],
        ["200+", "More than 200"],
      ],
      crmActual: [
        ["ninguno", "None"],
        ["gohighlevel", "Go High Level"],
        ["hubspot", "HubSpot"],
        ["salesforce", "Salesforce"],
        ["pipedrive", "Pipedrive"],
        ["otro", "Other"],
      ],
      usaWhatsapp: [
        ["si", "Yes, actively"],
        ["si-sin-sistema", "Yes, but with no system"],
        ["no", "No"],
      ],
      tiempoPropuesta: [
        ["<1h", "Less than 1 hour"],
        ["1-8h", "Between 1 and 8 hours"],
        ["1-3d", "Between 1 and 3 days"],
        ["+3d", "More than 3 days"],
      ],
      objetivo: [
        "Qualify my leads better",
        "Automate follow-up",
        "Cut time spent on proposals",
        "Tidy up my CRM",
        "Build a system from scratch",
        "Other",
      ],
      urgencia: [
        ["prisa", "I'm in a hurry, let's move now (< 30 days)"],
        ["1-3meses", "I'm planning for 1-3 months"],
        ["explorando", "I'm exploring options"],
      ],
      presupuesto: [
        ["<1000", "Less than €1,000"],
        ["1000-3000", "Between €1,000 and €3,000"],
        ["3000-7000", "Between €3,000 and €7,000"],
        [">7000", "More than €7,000"],
      ],
      comoConociste: [
        ["linkedin", "LinkedIn"],
        ["google", "Google / SEO"],
        ["referido", "Someone recommended me"],
        ["redes", "Social media"],
        ["otro", "Other"],
      ],
    },
    success: {
      title: "Got it. I'll write to you within 24 h.",
      body: "I've received your diagnosis. If you want to move faster, you can book directly on my calendar.",
      button: "Book your slot now",
      note: "Or wait for my email. I'll review your request today.",
    },
  },
} as const;

export function getForm(lang: Lang) {
  return formContent[lang];
}
